# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_run:
    branches: ['main']
    workflows: ['Test']
    types: ['completed']

jobs:
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          
      - name: Get packages
        run: flutter pub get
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build apk
        run: flutter build apk
      - name: Build appbundle
        run: flutter build appbundle
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: BM-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload appbundle
        uses: actions/upload-artifact@v2
        with:
          name: BM-aab
          path: build/app/outputs/bundle/release/app-release.aab
  Publish:
    needs: ['Build']
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        delete_release: true # default: false
        tag_name: bleeding-edge # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: bleeding-edge
        name: Bleeding Edge
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          */*
        body: | 
          Automatically generated bleeding edge release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
