# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
      - name: Get firebase tools
        run: npm install -g firebase-tools
      - name: Get packages
        run: flutter pub get
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      # - name: Analyze code
      #   run: flutter analyze
      - name: Prep firebase
        run: firebase init emulators --token $(grep -Po '(?<=FIREBASE_TOKEN\s=).*' .env --color=never)
      - run: firebase emulators:start --token $(grep -Po '(?<=FIREBASE_TOKEN\s=).*' .env --color=never)
      - name: Test
        run: flutter test
